services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:8080

  rapi:
    build:
      context: ./r-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"